project_name: kubetap
env:
- CGO_ENABLED=0
before:
  hooks:
    - go mod download
builds:
- main: ./cmd/kubectl-tap/
  binary: kubectl-tap
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
  ignore:
    - goos: darwin
      goarch: 386
    - goos: darwin
      goarch: arm64
    - goos: darwin
      goarch: arm
    - goos: windows
      goarch: arm64
    - goos: windows
      goarch: arm
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'kubetap_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^scripts:'
    - '^proxies:'
# Goreleaser brew only provides binary packages, which is pretty
# useless on Mac as of notarization.
# We instead build from source, requiring the Go toolchain which
# is acceptable, as kubernetes-cli already requires this.
#brews:
#  -
#    # brew only supports one 32-bit ARM version
#    goarm: 6
#    github:
#      owner: soluble-ai
#      name: homebrew-kubetap
#    commit_author:
#      name: kubetap-bot
#      email: devnull@soluble.ai
#    homepage: "https://github.com/soluble-ai/kubetap"
#    description: "Proxy Kubernetes Services with ease"
#    test: |
#      system "#{bin}/kubectl-tap version"
